config/routes.rb
Documents::Application.routes.draw do
  resources :documents
  
  resources :tags, :only => [:index, :show]
  
  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'documents#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  fields do
    title :string
    content :text
    uuid :string
    timestamps
  end
  attr_accessible :title, :content, :uuid
  
  # User -> Documents
  belongs_to :user, :inverse_of => :documents
  # Documents <-> Tags
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	fields do
		name :string
	end
	has_and_belongs_to_many :documents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fullname
  # attr_accessible :title, :body
  
  has_many :documents, :inverse_of => :user
  

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    
    if user = self.find_by_email(data.email)

      user
    else # Create a user with a stub password. 
      self.create!(:email => data.email, :password => Devise.friendly_token[0,20], :fullname => data.name) 
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    def index
      @documents = Document.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @documents }
      end
    end
  
end

app/controllers/documents_controller.rb
require 'crocodoc'

class DocumentsController < ApplicationController

include Crocodoc
    
  before_filter :authenticate_user!
  
  
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
    
    @session = create_session(@document.uuid, :downloadable => true)[:session]
    @embeddable_url = session_viewer_url(session)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create

    @document = Document.new(params[:document])
    @document.user = current_user
    
    # Upload the document to Crocodoc and get the UUID 
    
    # Get the path for the temporary file and add the appropriate extension
    tmp_file_path = params[:attachment].path
    file_extension = params[:attachment].original_filename.scan(/\.\w+$/)[0]
    File.rename(tmp_file_path, tmp_file_path + file_extension)
    tmp_file_path += file_extension
    
    # Read the file
    attachment = File.new(tmp_file_path, "r")
    
    # Upload the file to Crocodoc
    uuid = upload(attachment)[:uuid]
    
    logger.debug "UUID returned is #{uuid}" 
    
    @document.uuid = uuid   
	
	# Tag List
	
  	taglist = JSON.parse(params[:tags])
  	logger.debug "Taglist: #{taglist}"
  	taglist.each do |tagname|
  		tag = (Tag.where(:name => tagname).exists?) ? Tag.where(:name => tagname) : Tag.new(:name => tagname)
  		@document.tags << tag
  		logger.debug "Assigning tag '#{tagname}' to document (#{@document.id})"
  	end
  	
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, :notice => "" }
        format.json { render :json => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.json { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, :notice => 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /documents
  # GET /documents.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tags }
    end
  end
  
  def show
  	@tag = Tag.find(params[:id])
  	
  	respond_to do |format|
  		format.html # show.html.erb
  		format.json { render :json => @tag }
  	end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => { :multipart => true } do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  	<input class="button" id="document_attachment" name="attachment" type="file"/>

	<div class="field">
		<%= f.text_field :title, :placeholder => "Title" %>
	</div>
	
<!--	<div class="field">
		<%= f.label :content %><br/>
		<%= f.text_area :content %>
	</div>-->
	
	<script>
		$(document).ready(function() {
			$("#tag-field").tag({ height: 40 });
		});
	</script>
	
	<div id="tag-field"></div>
	
<!--	<div class="tag-box">
		<div class="tags">
			<div class="tag-tag">Tag Name</div>
			<div class="tag-tag">These</div>
			<div class="tag-tag">Beautiful?</div>
		</div>
		<input type="text" class="tag-input" placeholder="Add a tag..."/>
	</div>-->
	
	

	

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div id="documents-container">

<h1>All Documents</h1>

<!--<div class="tag-box">
	<div class="tags">
		<div class="tag-tag">Tag Name</div>
		<div class="tag-tag">These</div>
		<div class="tag-tag">Beautiful?</div>
	</div>
	<input type="text" class="tag-input" placeholder="Add a tag..."/>
</div>-->

<% @edit_privileges = false %>
<% @documents.each do |document| %>
	<article>	
		<h2><%= link_to(document.title, document) %></h2>
		<p class="summary"></p>
	<% if @edit_privileges then %>
    	<%= link_to 'Edit', edit_document_path(document), :class => "edit" %>
    	<%= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
    </article>

<% end %>

</div>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
 <script src="//static-v2.crocodoc.com/core/docviewer.js"></script>
 <script src="//crocodoc.com/webservice/document.js?session=<%= @session %>"></script>

<p id="notice"><%= notice %></p>

<aside id="sidebar">
   
   <h1><%= @document.title %></h1>
<!--   <p>Uploaded by <%= @document.user.fullname %></p>
   <p>Rating: ****</p>-->
   
   <div id="tags">
   <% @document.tags.each do |tag| %>
   	<div class="tag"><%= tag.name %></div>
   <% end %>
   	<div class="tag">Example Tag 1</div>
   	<div class="tag">Example Tag 2</div>
   </div>

	<div class="button blue"><a href="">Download</a></div>
	
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=280152582078774";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
	<div class="fb-like" data-send="true" data-layout="box_count" data-width="450" data-show-faces="true"></div>

</aside>

<div id="document-container">
	<div id="docviewer">
		  <script type="text/javascript">
		  	var docviewer = new DocViewer({ "id": "docviewer" });
		  </script>
	</div>
</div>
	
</div>


<!--<div class="document-info">
	
	<h1><%= @document.title %></h1>
	<span class="author">Uploaded by <%= @document.user.fullname %></span>
	
<!--	<% if current_user == @document.user %>
	<div class="button blue"><%= link_to 'Edit', edit_document_path(@document) %></div>
	<% end %>
	
	<div class="button blue"><%= link_to "Copy Short URL", @document %></div>
	
	<div id="tags">
	<% @document.tags.each do |tag| %>
		<div class="tag"><%= tag.name %></div>
	<% end %>
		<div class="tag">Example Tag 1</div>
		<div class="tag">Example Tag 2</div>
	</div>--*>

</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Documents</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<script type="/json2.js"></script>

<!-- jQuery -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<!-- Custom Fonts -->
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css' />

<link rel="stylesheet" href="/tags.css"/>
<script src="/tags.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>



</head>
<body>
	
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
   <header>
    <ul class="menu lgray slide">
    	<li><%= link_to "StudyMe", "/" %></li>
    	<li>
    		<%= link_to "Tags", "/tags" %>
    		<ul>
    			<% Tag.all.each do |tag| %>
    				<li><%= link_to tag.name, tag %></li>
    			<% end %>
    		</ul>
    	</li>
    	<li class="floatr"><%= link_to "Upload", new_document_path %></li>
	<% if user_signed_in? %>
		<li class="floatr">
			<%= link_to current_user.fullname, "" %>
			<ul>
				<!--<li><a href=""><%= current_user.email %></a></li>-->
				<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
			</ul>
		
		</li>
		
<!--		<li><a>Search</a></li>-->
	<% else %>
		<li><%= link_to('Login', new_user_session_path)  %></li>
	<% end %>
    </ul>
   </header>
   
   <div id="content">
  	<%= yield %>
   </div>
   	
  <footer>
  	<span class="copyright">&copy; 2012 Suck A Fat Cock Inc.</span>
  </footer>
   


</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul>
<% @tags.each do |tag| %>
	<li><%= tag.name %><%= link_to tag.name, tag_path(tag) %></li>
<% end %>
</ul>

app/views/tags/show.html.erb
<h1>Documents tagged '<%= @tag.name %>'</h1>
<ul>
<% @tag.documents.each do |document| %>
	<li><%= link_to document.title, document %></li>
<% end %>
</ul>